import type { Metadata } from "next";
import { Instrument_Serif } from "next/font/google";
import "./globals.css";

const geistSans = Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Serif.variable}`}>
        {children}
      </body>
    </html>
  );
}
